--USE [AH3111ODZ]

/****** Object:  Table [dbo].[R_MSG]    Script Date: 2/2/2018 7:37:51 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ZZR_MSG](
	[MSG_CD] [varchar](5) NOT NULL,
	[MSG_TXT] [varchar](254) NOT NULL,
	[MSG_SEV] [int] NOT NULL,
	[MSG_EXPL] [text] NULL,
	[OV_LVL] [int] NULL,
	[AMS_ROW_VERS_NO] [bigint] NULL,
	[MSG_TXT_UP] [varchar](254) NULL,
	[TBL_LAST_DT] [datetime] NULL,
 CONSTRAINT [PK_RMSG_R_MSGMSG_CD_] PRIMARY KEY CLUSTERED 
(
	[MSG_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
