PRINT 'BEGIN TRANSACTION'
BEGIN TRANSACTION
GO

SET QUOTED_IDENTIFIER ON
GO

--BUILD_001

--ADVHR00123564
--DDL

IF (@@TRANCOUNT = 0)
    SET NOEXEC ON
GO

--BUILD_002

--ADVHR00121151
--DDl

alter table LEAVE_BANK alter column DONA_AM_SC VARCHAR(12)
GO

--ADVHR00124291
--DDL
CREATE INDEX N2_TIMEIDOCLINE_TIMEI_DOC_LIN ON TIMEI_DOC_LINE( 
DOC_ID, 
INTERNAL_EMPL_ID)
GO

--ADVHR00125335
--DDl

ALTER VIEW SUPERVISOR_VW ( INTERNAL_EMPL_ID, EMPLOYEE_ID, DISPLAY_NAME, SUPR_EMPL_ID ) AS SELECT INTERNAL_EMPL_ID, EMPLOYEE_ID, DISPLAY_NAME, EMPLOYEE_ID FROM EMPL 
GO


--BUILD_003

--ADVHR00126113
--DDL

sp_rename 'CATG_CAP' , 'CATG_CAP_TEMP'
GO

CREATE TABLE CATG_CAP(
PERFKEY   CHAR(18) NOT NULL , 
CATG_CAP_CD   VARCHAR(10) NOT NULL , 
EFFECTIVE_DT   DATETIME NOT NULL , 
EXPIRATION_DT   DATETIME NULL , 
CATG_LONG_DD   VARCHAR(60) NULL , 
CATG_SHORT_DD   VARCHAR(15) NOT NULL , 
ANNUAL_CAP_AM   NUMERIC(10,2) NULL , 
SBJT_GRS_CAP_AM   NUMERIC(10,2) NULL , 
CATG_TYPE   VARCHAR(4) NULL , 
PAYOT_CAP_AM   INT NULL , 
	USE_PY_PRD_END_FL   BIT NULL , 
ACTN_CD   INT NULL , 
AMS_ROW_VERS_NO   BIGINT NULL , 
LAST_UPDATE_DT   DATETIME NULL , 
LAST_UPDATE_USERID   VARCHAR(16) NULL  )
GO


INSERT INTO CATG_CAP (
PERFKEY,
CATG_CAP_CD,
EFFECTIVE_DT,
EXPIRATION_DT,
CATG_LONG_DD,
CATG_SHORT_DD,
ANNUAL_CAP_AM,
SBJT_GRS_CAP_AM,
CATG_TYPE,
PAYOT_CAP_AM,
ACTN_CD,
AMS_ROW_VERS_NO ,
LAST_UPDATE_DT,
LAST_UPDATE_USERID )
SELECT 
PERFKEY,
CATG_CAP_CD,
EFFECTIVE_DT,
EXPIRATION_DT,
CATG_LONG_DD,
CATG_SHORT_DD,
ANNUAL_CAP_AM,
SBJT_GRS_CAP_AM,
CATG_TYPE,
PAYOT_CAP_AM,
ACTN_CD,
AMS_ROW_VERS_NO ,
LAST_UPDATE_DT,
LAST_UPDATE_USERID FROM CATG_CAP_TEMP
GO


drop table CATG_CAP_TEMP
GO

ALTER TABLE CATG_CAP ADD CONSTRAINT U_U1CATGCAP_CATG_CAPPERFKEY_ UNIQUE(
PERFKEY)
GO

ALTER TABLE CATG_CAP ADD CONSTRAINT PK_CATGCAP_CATG_CAPCATG_CAP_CD PRIMARY KEY( 
CATG_CAP_CD, 
EFFECTIVE_DT)
GO

CREATE INDEX N1_CATGCAP_CATG_CAP ON CATG_CAP( 
LAST_UPDATE_DT)
GO

CREATE TRIGGER [dbo].[TU_CATGCAP] ON [dbo].[CATG_CAP] FOR INSERT, UPDATE
AS
  UPDATE CATG_CAP
  SET CATG_CAP.LAST_UPDATE_DT = GETDATE()
  FROM INSERTED
  WHERE INSERTED.CATG_CAP_CD = CATG_CAP.CATG_CAP_CD
  AND INSERTED.EFFECTIVE_DT = CATG_CAP.EFFECTIVE_DT

GO


--ADVHR00125659
--DDL

ALTER TABLE PAY_COMP ALTER COLUMN PAY_PC NUMERIC(5,4)
GO

--END
SET QUOTED_IDENTIFIER OFF
GO


IF (@@ERROR <> 0 AND @@TRANCOUNT <> 0)
    ROLLBACK TRANSACTION
GO


-- 


IF (@@TRANCOUNT>0) 
BEGIN
    PRINT 'COMMIT TRANSACTION'
    COMMIT TRANSACTION
END
GO
